discord:
  name: "Your Bot"
  token: "YOURTOKEN"
  guild-id: 444222000
database:
  type: "SQL"

  sql:
    max-pool-size: 10
    host: "127.0.0.1"
    port: 3306
    database: "ranksync"
    user: "root"
    password: ""

ranks:
  discord:
    test:
      minecraft: "admin"
      discord: "Minecraft Administrator"
    kaas:
      minecraft: "mod"
      discord: "Minecraft Moderator"