# language:
# All available languages are available in the /plugins/RankSync/language/ directory
# For more information, see: https://github.com/Chickenpowerrr/RankSync/wiki/Language
# -
# discord:
#   update-non-synced: If the ranks from non-synced users should be removed
#   sync-names: If the usernames of users should be updated to their ingame name
#   name-format: The format for the name sync feature
#                - %discord_rank% The name of the rank in Discord
#                - %name% The Minecraft username
#   token: The Discord Token, for more information see:
#          https://github.com/Chickenpowerrr/RankSync/wiki/Getting-a-Discord-Token
#   permission-warnings: If the plugin should notify the console when it isn't able to
#                        perform a certain task
# database:
#   type: Yaml or SQL
# -
#   sql:
#     max-pool-size: Don't this if you don't know what it is
#     host: The host the SQL server is running on
#     port: The SQL server port, it is 3306 by default
#     database: The target database in the SQL server
#     user: The username to login into the SQL server
#     password: The password to login into the SQL server
# -
#   ranks: For more information see: https://github.com/Chickenpowerrr/RankSync/wiki/Ranks
#     discord: Don't touch this
#       administrator: A random UNIQUE prefix that is handy for you.
#                      The code doesn't do anything with it as long as it is UNIQUE.
#         name-format: Overwrites the default name-format for this specific rank
#         minecraft: The name of the Minecraft group. It is case sensitive
#         discord: The name of the Discord group. It is case insensitive
# -
# For more information see:
# - https://github.com/Chickenpowerrr/RankSync/wiki
# - https://discord.gg/zDsmRTd

language: english

discord:
  update-non-synced: false
  sync-names: false
  name-format: "%discord_rank% << %name%"
  token: "YOURTOKEN"
  guild-id: 444222000
  permission-warnings: true
database:
  type: "yaml"

  sql:
    max-pool-size: 10
    host: "127.0.0.1"
    port: 3306
    database: "ranksync"
    user: "root"
    password: ""

ranks:
  discord:
    administrator:
      minecraft: "admin"
      discord: "Minecraft Administrator"
    moderator:
      name-format: "Mod << %name%"
      minecraft: "mod"
      discord: "Minecraft Moderator"
    vip:
      name-format: "%name%"
      minecraft: "VIP"
      discord:
        - "VIP"
        - "Donator"